name: Esteira de deploy do Seekers
on: 
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          GIT_REPOSITORY: ${{ github.repository }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          REPOSITORY=$(basename $GIT_REPOSITORY)
          docker build -t $DOCKER_USERNAME/$REPOSITORY:$GITHUB_SHA -t $DOCKER_USERNAME/$REPOSITORY:latest .

      - name: Push Docker image to Docker Hub
        env:
          GIT_REPOSITORY: ${{ github.repository }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          REPOSITORY=$(basename $GIT_REPOSITORY)
          docker push $DOCKER_USERNAME/$REPOSITORY:$GITHUB_SHA
          docker push $DOCKER_USERNAME/$REPOSITORY:latest
